apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    admission-webhook: enabled
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-webhook
  labels:
    admission-webhook: disabled
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-without-label
spec:
  containers:
  - name: nginx
    image: nginx
