apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - name: example-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVU1h6emMvT0VDSHlWSDJBZDB5eUkvdWV5c2Nrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdPVEl4Ck1qRTBNVEF3V2hjTk1qY3dPVEl3TWpFME1UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKMlNUYXVDCm1NOWRyQVRzTGF4cmN4aWt3WStHMFpRYUpDcDdJaUZVeVBLM1RQY1V3bHdpWUZJMVlXOFRZSHFob1JkanBOaXkKeVZKTDNEYWxFWmZ2ejNkaEZaL1lyeHdyNHBWQ1JkQWFDbVloNmdKVU9lQm95aWN2ZVM2Vmk3YVRNRHRPZ2dsRwpqc3UrZWFKQzg4SEw2a2RZUU01ZzBZK3NWTWJHcUdxTGIyNnFnRnBtTG1mdGlPTVBxdlNEaG5DOFM2dlBLT3kxCnplN1ZYUHdUOFhNc1E1MVZEVTUzcHdISHA1akVUMkg1WlFVQTVYMGlpSUFPSmhleU5oZlNKclhqdnZ1aklhcmMKNm9HTDRNMmNlRTU3RHFQdEFhbWRtd3J0QWhnUUJ5V0NJMW9sdS9NUkdubXErc3NjTU91UloyejlYN3kxWlRBTgp0MXQ2SEwrVTd3WE5JSk1DQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkdncW9LZ1ZRcENqeUtiMHJueWhLa2FDM25aNE1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUJjMDhITGg2anBvdlFlVGRFdEJ1b3d2TVhwUHcvakpqZHVWREYxVmJrS1ZxMmNnVkFud29jRAo5eXY3eFBTYWoxd05ZWGhDZGt2ZGUrL1h0a0JTVUk0WjJmSTZ5WVYwbUtsVFhNb3gvaXQ5S1AwN21ST1hpRUdtCkQ4SGFiVFBlMEVzcGQ5YVpMcUFwYURSbXVRZDJnZitrZHIzQjA2QU52UFVNVWFXNkQyL3lsMlMvems4dHFsZVEKRWNob1ZlY3RKd3JxSFlWOUJoamRXa2ZrWFQzZDE1WDBoUnJrWHFZQUM4UU1pNW9ESUdkK0VQTGNKc0NEVWZEWQpualBObVRoa2lTUFc2QnMvZFNwbnlPY1lncEtRUElOd3hkTWdkRnpUaEsxRGUvcDFYemdBdlpPRkQrNktUQ2lICk04Vk1JRlZrNHVmWUk2Z0tUZTNNYmVUU01UY0tSY0sxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
